version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "07:00"

  - package-ecosystem: 'docker'
    directory: '/*/*.Dockerfile'
    schedule:
      interval: "daily"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    target-branch: main
    labels:
      - dependencies

  - package-ecosystem: 'docker'
    directory: '/*/Dockerfile'
    schedule:
      interval: "daily"
      time: "07:00"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    labels:
      - dependencies
