version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    schedule:
      interval: "daily"
      time: "07:00"
  - package-ecosystem: docker
    directory: "elasticsearch"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
      - nlx-klein
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "mariadb"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "proxy"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "rabbitmq"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "redis"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "styleguide"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "varnish"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "webserver"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    target-branch: main
    reviewers:
      - nlx-sascha
      - nlx-lars
    labels:
      - dependencies
