name: 'Build basic docker container'

on:
  schedule:
    - cron: 0 4 * * THU
  push:
    branches:
      - main

jobs:
  docker:
    name: 'Build docker container'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: mariadb
            context: ./containers/mariadb
            target: ''
            build-args: ''
          - name: proxy
            context: ./containers/proxy
            target: ''
            build-args: ''
          - name: redis
            context: ./containers/redis
            target: ''
            build-args: ''
          - name: varnish
            context: ./containers/varnish
            target: ''
            build-args: ''
          - name: elasticsearch
            context: ./containers/elasticsearch
            target: ''
            build-args: ''
          - name: webserver-neos
            context: ./containers/webserver
            target: 'webserver-neos'
            build-args: ''
          - name: webserver-typo3
            context: ./containers/webserver
            target: 'webserver-typo3'
            build-args: ''
          - name: webserver-shopware
            context: ./containers/webserver
            target: 'webserver-shopware'
            build-args: ''
          - name: webserver-static
            context: ./containers/webserver
            target: 'webserver-static'
            build-args: ''
          - name: styleguide
            context: ./containers/styleguide
            target: ''
            build-args: ''
          - name: php-7.2-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: |
              PHP_VERSION=7.2
              UBUNTU_VERSION=18.04
          - name: php-7.2-fpm-dev
            context: ./containers/php
            target: 'php-fpm-dev'
            build-args: |
              PHP_VERSION=7.2
              UBUNTU_VERSION=18.04
          - name: php-7.2-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: |
              PHP_VERSION=7.2
              UBUNTU_VERSION=18.04
          - name: php-7.2-cli-dev
            context: ./containers/php
            target: 'php-cli-dev'
            build-args: |
              PHP_VERSION=7.2
              UBUNTU_VERSION=18.04
          - name: php-7.2-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: |
              PHP_VERSION=7.2
              UBUNTU_VERSION=18.04
          - name: php-7.4-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: |
              PHP_VERSION=7.4
              UBUNTU_VERSION=20.04
          - name: php-7.4-fpm-dev
            context: ./containers/php
            target: 'php-fpm-dev'
            build-args: |
              PHP_VERSION=7.4
              UBUNTU_VERSION=20.04
          - name: php-7.4-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: |
              PHP_VERSION=7.4
              UBUNTU_VERSION=20.04
          - name: php-7.4-cli-dev
            context: ./containers/php
            target: 'php-cli-dev'
            build-args: |
              PHP_VERSION=7.4
              UBUNTU_VERSION=20.04
          - name: php-7.4-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: |
              PHP_VERSION=7.4
              UBUNTU_VERSION=20.04
          - name: php-8.1-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: |
              PHP_VERSION=8.1
              UBUNTU_VERSION=22.04
          - name: php-8.1-fpm-dev
            context: ./containers/php
            target: 'php-fpm-dev'
            build-args: |
              PHP_VERSION=8.1
              UBUNTU_VERSION=22.04
          - name: php-8.1-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: |
              PHP_VERSION=8.1
              UBUNTU_VERSION=22.04
          - name: php-8.1-cli-dev
            context: ./containers/php
            target: 'php-cli-dev'
            build-args: |
              PHP_VERSION=8.1
              UBUNTU_VERSION=22.04
          - name: php-8.1-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: |
              PHP_VERSION=8.1
              UBUNTU_VERSION=22.04

    env:
      DOCKER_IMAGE: ghcr.io/netlogix/docker/${{ matrix.image.name }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.image.context }}
          target: ${{ matrix.image.target }}
          file: ${{ matrix.image.context }}/Dockerfile
          build-args: ${{ matrix.image.build-args }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE }}
          platforms: linux/amd64,linux/arm64
#          cache-from: type=gha, scope=${{ github.workflow }}
#          cache-to: type=gha, scope=${{ github.workflow }}
