name: 'Build basic docker container'

on:
  schedule:
    - cron: 0 4 * * THU
  push:
    branches:
      - main

jobs:
  docker:
    name: 'Build docker container'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: mariadb
            context: ./containers/mariadb
            target: ''
            build-args: ''
          - name: proxy
            context: ./containers/proxy
            target: ''
            build-args: ''
          - name: redis
            context: ./containers/redis
            target: ''
            build-args: ''
          - name: varnish
            context: ./containers/varnish
            target: ''
            build-args: ''
          - name: elasticsearch
            context: ./containers/elasticsearch
            target: ''
            build-args: ''
          - name: webserver-neos
            context: ./containers/webserver
            target: 'webserver-neos'
            build-args: ''
          - name: webserver-typo3
            context: ./containers/webserver
            target: 'webserver-typo3'
            build-args: ''
          - name: webserver-shopware
            context: ./containers/webserver
            target: 'webserver-shopware'
            build-args: ''
          - name: webserver-static
            context: ./containers/webserver
            target: 'webserver-static'
            build-args: ''
          - name: php-7.4-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: 'PHP_VERSION=7.4'
          - name: php-7.4-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: 'PHP_VERSION=7.4'
          - name: php-7.4-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: 'PHP_VERSION=7.4'
          - name: php-8.0-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: 'PHP_VERSION=8.0'
          - name: php-8.0-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: 'PHP_VERSION=8.0'
          - name: php-8.0-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: 'PHP_VERSION=8.0'
          - name: php-8.1-fpm
            context: ./containers/php
            target: 'php-fpm'
            build-args: 'PHP_VERSION=8.1'
          - name: php-8.1-cli
            context: ./containers/php
            target: 'php-cli'
            build-args: 'PHP_VERSION=8.1'
          - name: php-8.1-cron
            context: ./containers/php
            target: 'php-cron'
            build-args: 'PHP_VERSION=8.1'

    env:
      DOCKER_IMAGE: ghcr.io/netlogix/docker/${{ matrix.image.name }}:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.image.context }}
          target: ${{ matrix.image.target }}
          file: ${{ matrix.image.context }}/Dockerfile
          build-args: ${{ matrix.image.build-args }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
