name: Generate dependabot.yml

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Generate dependabot.yml
        uses: Makeshift/generate-dependabot-glob-action@master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        commit-message: 'FEATURE: Update dependabot.yml'
        title: 'Update dependabot.yml'
        assignees: nlx-sascha
