name: 'Build mysql docker image'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions: 
  packages: write

on:
  schedule:
    - cron: 0 18 * * SAT
  push:
    branches:
      - main
    paths:
      - mysql/**
      - .github/workflows/mysql.yml
  pull_request:
    branches:
      - main
    paths:
      - mysql/**
      - .github/workflows/mysql.yml
  workflow_dispatch:
    inputs: {}

jobs:
  build-docker-image:
    name: 'Build mysql-${{ matrix.image.version }} docker image'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        image:
          - version: 8.0
            file: 8.0.Dockerfile
          - version: 8.4
            file: 8.4.Dockerfile
          - version: latest
            file: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (mysql)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./mysql
          target: mysql
          file: ./mysql/${{ matrix.image.file || 'Dockerfile' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/meggernet/docker/mysql:${{ matrix.image.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}-mysql
          cache-to: type=gha, scope=${{ github.workflow }}-mysql, mode=max

